# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "tiquete"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"
template: "template_toolkit"
engines:
   template:
     template_toolkit:
       start_tag: '<%'
       end_tag:   '%>'

data: lib/tickets.csv
mail_contacto: c@hipermegared.com.ar
mail_webmaster: w@hipermegared.com.ar
pass_admin: secretisimo123


# Mails! Para enviar desde la app.
mail_enable: 0
mail_send_from: tickets@hipermegared.com.ar
mail_send_reply: c@hipermegared.com.ar
mail_send_encoding: ISO-8859-1
mail_send_charset: quoted-printable

# Configuraciones para limitar la cantidad de tickets abiertos por dominio/Contacto
maximos_tickets_per_mail: 3
maximos_tickets_per_domain: 1

# defaults para los ticketes
default_tik_st: "Abierto"
default_tik_dev: "Ticket asignado para su pronta resoluci&oacute;n. Vuelva pronto!"
