# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "tiquete"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

# Log engine
# logger: "console"
#logger: "File"
#engines:
    #logger:
        #File:
            #log_dir: "/var/log/myapp"
            #file_name: "myapp.log"

#template: "simple"
template: "template_toolkit"
engines:
   template:
     template_toolkit:
       start_tag: '<%'
       end_tag:   '%>'


plugins:
    Auth::Extensible:
        login_page_handler: 'tiquete::login_page_handler'
        permission_denied_page_handler: 'tiquete::permission_denied_page_handler'
        disable_roles: 1
        user_home_page: '/all'
        exit_page: '/'
        realms:
            config:
                provider: Config
                users:
                    - user: admin
                      pass: secretisimo123






# M A I N
data: lib/tickets.csv
pass_admin: secretisimo123


# Mails! Para enviar desde la app.
mail_enable: 0
mail_contacto: c@hipermegared.com.ar
mail_webmaster: w@hipermegared.com.ar
mail_send_from: tickets@hipermegared.com.ar
mail_send_reply: c@hipermegared.com.ar
mail_send_encoding: ISO-8859-1
mail_send_charset: quoted-printable

# Configuraciones para limitar la cantidad de tickets abiertos por dominio/Contacto
max_tiks_per_mail: 3

# defaults para los ticketes
default_tik_st: "Abierto"
default_tik_dev: "Ticket asignado para su pronta resoluci&oacute;n. Vuelva pronto!"
min_longitud_descripcion_tik: 30
precio_hora_soporte: "$400"

devolucion_primera: "Escriba debajo la devolución para el cliente."
devolucion_retoques: "Cuidado! esta retocando la devolución prexistente."

#Mail templates

mail_tmpl_id: "El ID es: "
mail_tmpl_url: "La URL es: "
mail_tmpl_pie: "---\nc@hipermegared.com.ar\nHMR. 2016"
mail_tik_inicio: |
    Su ticket se ha inicializado exitosamente.
    Este mensaje confirma su llegada a los administradores para su pronta resolución.
    Le recomendamos conservar el link y el identificador de su ticket para futura referencia.
mail_tik_open: |
    Se abrió un nuevo ticket.
mail_tik_closed: |
    Se cerró su previo ticket.

